name: YarnUpgrade
on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch: {}
jobs:
  upgrade:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.17.0
      - name: Set git identity
        run: |-
          git config user.name "Auto-yarn-upgrade"
          git config user.email "github-actions@github.com"
      - run: yarn upgrade
      - run: yarn projen:upgrade
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}
          push-to-fork: cdk-automation/cdk-serverless-lamp
          commit-message: "chore: yarn upgradae"
          branch: auto/yarn-upgrade
          title: "chore: upgrade projen and yarn"
          body: This PR upgrades projen and yarn upgrade to the latest version
          labels: auto-merge
    container:
      image: jsii/superchain
